//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftDiary.Web.CalendarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalendarService.ICalendarService")]
    public interface ICalendarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarService/GetAll", ReplyAction="http://tempuri.org/ICalendarService/GetAllResponse")]
        ShiftDiary.DTO.Calendar[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarService/GetCalendar", ReplyAction="http://tempuri.org/ICalendarService/GetCalendarResponse")]
        ShiftDiary.DTO.Calendar GetCalendar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarService/Save", ReplyAction="http://tempuri.org/ICalendarService/SaveResponse")]
        void Save(ShiftDiary.DTO.Calendar obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarService/Delete", ReplyAction="http://tempuri.org/ICalendarService/DeleteResponse")]
        void Delete(ShiftDiary.DTO.Calendar obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalendarServiceChannel : ShiftDiary.Web.CalendarService.ICalendarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalendarServiceClient : System.ServiceModel.ClientBase<ShiftDiary.Web.CalendarService.ICalendarService>, ShiftDiary.Web.CalendarService.ICalendarService {
        
        public CalendarServiceClient() {
        }
        
        public CalendarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalendarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShiftDiary.DTO.Calendar[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public ShiftDiary.DTO.Calendar GetCalendar(int id) {
            return base.Channel.GetCalendar(id);
        }
        
        public void Save(ShiftDiary.DTO.Calendar obj) {
            base.Channel.Save(obj);
        }
        
        public void Delete(ShiftDiary.DTO.Calendar obj) {
            base.Channel.Delete(obj);
        }
    }
}
